name: CI and CD

on:
  push:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Intall Node Packages
        run: npm install
      - name: Predeploy Step
        run: npm run generate
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
          follow_symlinks: true
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
